"""add booking fields

Revision ID: 6814730d5ccf
Revises: 
Create Date: 2026-07-10 00:43:15.837649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6814730d5ccf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.drop_column('session_time')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('session_date')
        batch_op.drop_column('price')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('session_date', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('session_time', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('currency')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
